# config.yaml
Database:
  Path: STRING
  EncryptionKey: STRING #Base64
Log:
  Path: STRING
  GormOutputEnabled: BOOL
Api:
  Port: INT
  JWTKey: STRING
  UseSwagger: BOOL
  AuthenticationRequired: BOOL
PDF:
  Path: STRING

SECRETS:
  Use: BOOL
  Environment: STRING # prod, dev, staging
  WorkspaceID: STRING
  ClientID: STRING
  ClientSecret: STRING
  JWTKey: BOOL # use secretprovider or configfile
  DBEncryptionKey: BOOl # use secretprovider or configfile