name: Test

on:
  push:
    branches:
      - '*'
    tags:
      - '!v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1

      - name: Store config
        run: |
          cat << EOF > config.yaml
          Database:
            Path: $HOME/apps/mpt_testing_enc
            EncryptionKey: FpQYpOAXmYTMiRDb33dnyh8OFaHRgWHOTvKxjWTwsCM=
          Log:
            Path: $HOME/apps/mpt/logs
            LevelDB: 2 # INFO = 0, WARNING = 1, ERROR = 2
          Api:
            Port: 9000
            AuthenticationRequired: true
            JWTKey: 6z5ZeRU!uW#bD9r^9nF&ijn@j2@!2NMAh^vXSJS$f5^HZTSkvGN%A9xj5qgR8Be9A6Ew$$xzKybe3NTozKJJ6MZAB9JUip9AWDkZgu$i6%gQKojZ%QLQzEbN6N!AWkwz
          PDF:
            Path: $HOME/apps/mpt/pdf
          EOF

      - name: Prepare env
        run: go run test/prep.go

      - name: execute Tests
        run: GOMAXPROCS=1 go test ./...